export const siteContent = {
  brand: "RETATRUTIDE",
  navigation: [
    { label: "About", href: "#about" },
    { label: "How it works", href: "#how-it-works" },
    { label: "Product", href: "#product" },
    { label: "Quality", href: "#quality" },
    { label: "FAQ", href: "#faq" },
  ],
  hero: {
    eyebrow: "Experimental peptide-based drug",
    title: "Retatrutide",
    body: "Retatrutide is an experimental peptide-based drug developed for weight loss and metabolic normalization. It acts through a triple mechanism by activating the GLP-1, GIP, and glucagon receptors.",
    primaryCta: "Review product information",
    secondaryCta: "How it works",
    proof: "Laboratory report available · Batch 82188",
  },
  trustItems: [
    { title: "Laboratory analysis", detail: "Supplied report available to inspect" },
    { title: "Batch 82188", detail: "Batch number shown on the report" },
    { title: "10.77 mg", detail: "Content reported by the laboratory" },
    { title: "99%", detail: "Purity reported by the laboratory" },
  ],
  whatIs: {
    eyebrow: "What is Retatrutide",
    title: "A triple-mechanism peptide-based drug.",
    body: [
      "Retatrutide is an experimental peptide-based drug developed for weight loss and metabolic normalization.",
      "It acts through a triple mechanism by activating the GLP-1, GIP, and glucagon receptors — hormones that regulate appetite, blood sugar, and energy expenditure.",
      "This unique combination currently makes it one of the most promising new candidates for the treatment of obesity and metabolic disorders.",
      "And now, Retatrutide is finally available in our shop for those looking to explore its potential firsthand.",
    ],
    note: "Category: Peptide · Purpose: Weight loss",
    receptors: ["GLP-1", "GIP", "Glucagon"],
    outcomes: ["Appetite", "Blood sugar", "Energy expenditure"],
  },
  howItWorks: {
    eyebrow: "How Retatrutide works",
    title: "Three receptors. One combined mechanism.",
    intro: "Retatrutide acts on three key hormonal receptors involved in food response and metabolic regulation: GLP-1, GIP, and the glucagon receptor. Their combined activation leads to appetite suppression, improved glucose control, and enhanced fat burning.",
    receptors: [
      {
        number: "01",
        title: "GLP-1",
        paragraphs: [
          "GLP-1 (glucagon-like peptide-1) is a hormone secreted by the gut after eating. It signals the brain that the body has received enough food, promoting early satiety and reducing hunger for several hours. It also slows gastric emptying, which prolongs the feeling of fullness.",
          "Beyond appetite control, GLP-1 stimulates the pancreas to release insulin precisely when blood sugar rises — particularly important for people with insulin resistance. It also lowers glucagon secretion, a hormone that raises blood sugar. This dual mechanism helps restore proper metabolic balance in those with excess weight or metabolic dysfunction.",
        ],
      },
      {
        number: "02",
        title: "GIP",
        paragraphs: [
          "GIP (glucose-dependent insulinotropic peptide) is another hormone released after meals. It helps regulate blood sugar but in a different way than GLP-1. GIP amplifies the body’s insulin response, especially after consuming carbohydrates and fats.",
          "It enhances insulin production and improves the ability of cells to absorb glucose, promoting its use for energy instead of leaving it in circulation. Persistent high blood sugar can overwork the pancreas, increase systemic inflammation, and accelerate fat accumulation — all of which raise diabetes risk. GIP also suppresses hepatic glucose production and may help regulate lipid metabolism by limiting fat storage.",
          "Interestingly, GIP on its own has limited impact, but in combination with GLP-1, the results are significantly stronger — leading to greater blood sugar control and more effective weight loss.",
        ],
      },
      {
        number: "03",
        title: "Glucagon",
        paragraphs: [
          "Glucagon is a hormone that functions opposite to insulin. While insulin promotes nutrient storage after eating, glucagon is activated during fasting or low blood sugar. It triggers the mobilization of internal energy stores: breaking down glycogen in the liver, initiating lipolysis (fat breakdown), and stimulating glucose production from amino acids.",
          "When glucagon receptors are artificially activated — as with Retatrutide — the body increases energy expenditure, even at rest. Lipolysis intensifies, so fat stored in adipose tissue is broken down and used as fuel.",
        ],
      },
    ],
  },
  whoFor: {
    eyebrow: "Who may benefit",
    title: "Who may benefit from Retatrutide?",
    intro: "Select a topic to review the information provided for that group.",
    cards: [
      {
        title: "Lose weight and control appetite",
        body: "If you’re looking to lose weight and control your appetite without extreme diets or starvation — Retatrutide reduces appetite and prolongs the feeling of fullness, helping you eat less and comfortably shed excess weight.",
      },
      {
        title: "Insulin resistance, metabolic syndrome, or prediabetes",
        body: "If you have insulin resistance, metabolic syndrome, or prediabetes — the drug enhances insulin sensitivity and supports blood sugar regulation.",
      },
      {
        title: "Obesity and related conditions",
        body: "If you suffer from obesity and related conditions like high blood pressure, fatigue, or inflammation Retatrutide helps reduce the strain on internal organs and improves your metabolic background.",
      },
      {
        title: "Diagnosed type 2 diabetes",
        body: "If you’ve been diagnosed with type 2 diabetes — it can help better manage blood glucose, reduce food cravings, and serve as an additional therapeutic tool.",
      },
      {
        title: "Prevent fatty liver disease",
        body: "If you aim to prevent fatty liver disease — Retatrutide may lower liver fat levels and reduce systemic inflammation.",
      },
    ],
  },
  product: {
    eyebrow: "Product",
    title: "One product. One dosage.",
    name: "Retatrutide",
    dosage: "10 mg / vial",
    description: "A single-dosage peptide presentation: Retatrutide 10 mg.",
    badges: ["Single product", "Single dosage"],
    specs: [
      { label: "Composition", value: "Retatrutide 10 mg" },
      { label: "Category", value: "Peptide" },
      { label: "Purpose", value: "Weight loss" },
      { label: "Form", value: "Vial with lyophilized powder + 1 ml ampoule of injection water reconstitution" },
      { label: "Administration", value: "Subcutaneous injections" },
    ],
    cta: "How to get it",
    ctaHref: "#how-to-get",
    detailCta: "Product details",
    disclosureTitle: "Product information",
    disclosureBody: "Composition: Retatrutide 10 mg. Category: Peptide. Purpose: Weight loss. Form: Vial with lyophilized powder + 1 ml ampoule of injection water reconstitution. Administration: Subcutaneous injections.",
  },
  howToGet: {
    eyebrow: "How to get it",
    title: "A clear path to the next step.",
    steps: [
      { number: "1", title: "Product information", body: "Review the product, dosage, form, administration, storage, and laboratory information." },
      { number: "2", title: "Doctor’s prescription", body: "Retatrutide is a controlled medication and requires a doctor’s prescription." },
      { number: "3", title: "Purchase", body: "Continue to the purchasing website, where the commercial terms are shown." },
    ],
    cta: "Continue to purchasing website",
    ctaHref: "https://retatrutides.to/new/index.html",
  },
  quality: {
    eyebrow: "Quality & authenticity",
    title: "Documentation you can inspect.",
    body: "The supplied laboratory report is presented alongside the product identity and batch information so the available material can be reviewed directly.",
    report: {
      title: "Laboratory analysis report",
      image: `${import.meta.env.BASE_URL}assets/documents/retatrutide-lab-report.png`,
      alt: "Laboratory analysis report for DRADA Medical Retatrutide batch 82188, reporting 10.77 mg content and 99% purity",
      date: "24 June 2026",
      batch: "82188",
      content: "10.77 mg",
      purity: "99%",
      cta: "View laboratory report",
      openLabel: "Open full-size report",
    },
    points: [
      { title: "Product identification", body: "The report identifies DRADA MEDICAL RETATRUTIDE, one vial, as a white powder in a glass vial." },
      { title: "Batch-linked report", body: "The supplied report identifies batch 82188 and order number 100015432." },
      { title: "Reported analysis", body: "The laboratory report records 10.77 mg content and 99% purity." },
    ],
    storageTitle: "How to store",
    storage: [
      "Keep the product refrigerated at 2–8°C (36–46°F).",
      "Do not freeze.",
      "Protect from light.",
      "Avoid frequent temperature changes (e.g., repeated removal from the fridge).",
      "Once reconstituted, keep refrigerated and use within approximately one month.",
    ],
    note: "Report values are reproduced from the supplied document. Review the full report before relying on individual figures.",
  },
  purchase: {
    eyebrow: "Purchase, delivery & payment",
    title: "Commercial information at the purchasing step.",
    cards: [
      { title: "Price & taxes", body: "The final price and applicable taxes are displayed on the purchasing website." },
      { title: "Payment", body: "Available payment options are displayed on the purchasing website." },
      { title: "Delivery area", body: "Delivery geography is provided on the purchasing website." },
      { title: "Delivery & returns", body: "Delivery timing and return terms are provided on the purchasing website." },
    ],
    nextStepTitle: "Continue to the purchasing website",
    nextStepBody: "Review the product and quality information, then continue to the purchasing website for the commercial terms.",
    primaryCta: "Continue to purchasing website",
    primaryHref: "https://retatrutides.to/new/index.html",
    secondaryCta: "View quality information",
    secondaryHref: "#quality",
  },
  reviews: {
    eyebrow: "Reviews",
    title: "Perspectives from across Europe.",
    items: [
      { initials: "AM", name: "Anna M.", country: "Germany", flagCode: "de", body: "The product information and the next steps are easy to find and understand." },
      { initials: "CL", name: "Camille L.", country: "France", flagCode: "fr", body: "The package details and supporting document are presented in a clear, reassuring format." },
      { initials: "SV", name: "Sophie V.", country: "Netherlands", flagCode: "nl", body: "The purchase guidance makes it clear which details should be confirmed before ordering." },
    ],
  },
  faqs: [
    { question: "What are the potential benefits of Retatrutide?", answer: "Weight loss, improved glucose control, reduced appetite." },
    { question: "Can Retatrutide be combined with anabolic steroids?", answer: "Yes, it can. Low doses of Retatrutide can be used to control appetite, especially during cutting cycles where maintaining a calorie deficit is important." },
    { question: "Is Retatrutide safe?", answer: "Early studies show it’s generally safe, but long-term data is limited." },
    { question: "Do I need a prescription for Retatrutide?", answer: "Yes, it's a controlled medication and requires a doctor's prescription. If you're comparing Retatrutide price or looking for a Retatrutide sale, ordering from us ensures you get one of the most competitive offers available. Just keep in mind that since it's a prescription-only product, you should be careful when transporting it across borders, as regulations may vary depending on the country." },
    { question: "How quickly will I notice results from Retatrutide?", answer: "Appetite reduction can start within the first 1–2 weeks. Noticeable weight loss typically appears after 3–4 weeks, with full effects building over several months." },
    { question: "What product is available?", answer: "Composition: Retatrutide 10 mg. Category: Peptide. Purpose: Weight loss. Form: Vial with lyophilized powder + 1 ml ampoule of injection water reconstitution. Administration: Subcutaneous injections." },
    { question: "Can I view the laboratory report?", answer: "Yes. The supplied laboratory report for DRADA MEDICAL RETATRUTIDE batch 82188 opens from the Quality & authenticity section." },
    { question: "How should Retatrutide be stored?", answer: "Keep the product refrigerated at 2–8°C (36–46°F). Do not freeze. Protect from light. Avoid frequent temperature changes. Once reconstituted, keep refrigerated and use within approximately one month." },
  ],
  footer: {
    statement: "Product information, documentation, and the next purchasing step in one place.",
    sellerNote: "Seller identity and direct contact details are provided on the purchasing website.",
    groups: [
      { title: "Seller & contact", links: [{ label: "Product", href: "#product" }, { label: "Purchase information", href: "#purchase" }, { label: "Contact information", href: "#seller-contact" }] },
      { title: "Sales & delivery", links: [{ label: "Price & payment", href: "#purchase" }, { label: "Delivery", href: "#purchase" }, { label: "Returns", href: "#returns" }] },
      { title: "Legal", links: [{ label: "Privacy", href: "#privacy" }, { label: "Cookie settings", href: "#cookies" }, { label: "Terms", href: "#terms" }, { label: "Regulatory information", href: "#regulatory" }] },
    ],
    disclosures: [
      { id: "seller-contact", title: "Seller & contacts", body: "Seller requisites and direct contact details are provided on the purchasing website." },
      { id: "privacy", title: "Privacy", body: "This landing page does not collect personal information through a form. The seller’s privacy information is provided on the purchasing website." },
      { id: "cookies", title: "Cookies", body: "This site uses essential cookies only. Optional analytics and marketing cookies are not active." },
      { id: "terms", title: "Terms", body: "Sales, payment, delivery, and return terms are provided on the purchasing website." },
      { id: "returns", title: "Delivery & returns", body: "Delivery and return information is provided on the purchasing website." },
      { id: "regulatory", title: "Regulatory information", body: "Retatrutide is a controlled medication and requires a doctor’s prescription. Regulations may vary depending on the country, including when transporting it across borders." },
    ],
    disclaimer: "Early studies show Retatrutide is generally safe, but long-term data is limited. A doctor’s prescription is required.",
  },
  mobileCta: "Review product information",
} as const;

export type SiteContent = typeof siteContent;
