export const siteContent = {
  brand: "RETATRUTIDE",
  navigation: [
    { label: "About", href: "#about" },
    { label: "How it works", href: "#how-it-works" },
    { label: "Product", href: "#product" },
    { label: "Quality", href: "#quality" },
    { label: "FAQ", href: "#faq" },
  ],
  hero: {
    eyebrow: "Lab Tested - 99% putity",
    title: "Retatrutide",
    lead: "A next-generation peptide developed to support weight loss.",
    body: "It works in three ways to help control appetite, support metabolism, and manage weight more effectively.",
    primaryCta: "How it works?",
    secondaryCta: "Consult an expert",
    secondaryHref: "https://driadashop.helpline.to/en-US/new-ticket",
    reviewHref: "https://peds.to/reviews/retatrutide.157/reviews",
    secondaryReviewHref: "https://www.eroids.com/reviews/driadashop.to",
  },
  trustItems: [
    { title: "99%", detail: "Third-party tested purity" },
    { title: "4.92 / 5", detail: "36 forum reviews", href: "https://peds.to/reviews/retatrutide.157/reviews" },
    { title: "EU delivery", detail: "Delivered across Europe" },
    { title: "Within 48 hours", detail: "Fast dispatch" },
  ],
  whatIs: {
    eyebrow: "What is Retatrutide",
    title: "WHAT IS RETATRUTIDE?",
    body: [
      "One molecule. Three metabolic pathways. Retatrutide is the first peptide designed to activate three key metabolic signals at the same time. This unique approach has attracted significant attention from researchers worldwide and represents a new direction in metabolic research. Here’s how it works — explained simply.",
    ],
    receptors: ["GLP-1", "GIP", "Glucagon"],
    outcomes: ["Appetite", "Blood sugar", "Energy expenditure"],
  },
  howItWorks: {
    eyebrow: "How Retatrutide works",
    title: "Three receptors. One combined mechanism.",
    intro: "Retatrutide acts on three key hormonal receptors involved in food response and metabolic regulation: GLP-1, GIP, and the glucagon receptor. Their combined activation leads to appetite suppression, improved glucose control, and enhanced fat burning.",
    receptors: [
      {
        number: "01",
        title: "GLP-1",
        paragraphs: [
          "GLP-1 (glucagon-like peptide-1) is a hormone secreted by the gut after eating. It signals the brain that the body has received enough food, promoting early satiety and reducing hunger for several hours. It also slows gastric emptying, which prolongs the feeling of fullness.",
          "Beyond appetite control, GLP-1 stimulates the pancreas to release insulin precisely when blood sugar rises — particularly important for people with insulin resistance. It also lowers glucagon secretion, a hormone that raises blood sugar. This dual mechanism helps restore proper metabolic balance in those with excess weight or metabolic dysfunction.",
        ],
      },
      {
        number: "02",
        title: "GIP",
        paragraphs: [
          "GIP (glucose-dependent insulinotropic peptide) is another hormone released after meals. It helps regulate blood sugar but in a different way than GLP-1. GIP amplifies the body’s insulin response, especially after consuming carbohydrates and fats.",
          "It enhances insulin production and improves the ability of cells to absorb glucose, promoting its use for energy instead of leaving it in circulation. Persistent high blood sugar can overwork the pancreas, increase systemic inflammation, and accelerate fat accumulation — all of which raise diabetes risk. GIP also suppresses hepatic glucose production and may help regulate lipid metabolism by limiting fat storage.",
          "Interestingly, GIP on its own has limited impact, but in combination with GLP-1, the results are significantly stronger — leading to greater blood sugar control and more effective weight loss.",
        ],
      },
      {
        number: "03",
        title: "Glucagon",
        paragraphs: [
          "Glucagon is a hormone that functions opposite to insulin. While insulin promotes nutrient storage after eating, glucagon is activated during fasting or low blood sugar. It triggers the mobilization of internal energy stores: breaking down glycogen in the liver, initiating lipolysis (fat breakdown), and stimulating glucose production from amino acids.",
          "When glucagon receptors are artificially activated — as with Retatrutide — the body increases energy expenditure, even at rest. Lipolysis intensifies, so fat stored in adipose tissue is broken down and used as fuel.",
        ],
      },
    ],
  },
  whoFor: {
    eyebrow: "Who may benefit",
    title: "Who may benefit from Retatrutide?",
    intro: "Select a topic to review the information provided for that group.",
    cards: [
      {
        title: "Lose weight and control appetite",
        image: `${import.meta.env.BASE_URL}assets/people/audiences/appetite.jpg`,
        imageAlt: "Woman representing appetite and weight-management goals",
        body: "If you’re looking to lose weight and control your appetite without extreme diets or starvation — Retatrutide reduces appetite and prolongs the feeling of fullness, helping you eat less and comfortably shed excess weight.",
      },
      {
        title: "Insulin resistance, metabolic syndrome, or prediabetes",
        image: `${import.meta.env.BASE_URL}assets/people/audiences/metabolic.jpg`,
        imageAlt: "Man representing metabolic health goals",
        body: "If you have insulin resistance, metabolic syndrome, or prediabetes — the drug enhances insulin sensitivity and supports blood sugar regulation.",
      },
      {
        title: "Obesity and related conditions",
        image: `${import.meta.env.BASE_URL}assets/people/audiences/obesity.jpg`,
        imageAlt: "Woman representing weight and metabolic health goals",
        body: "If you suffer from obesity and related conditions like high blood pressure, fatigue, or inflammation Retatrutide helps reduce the strain on internal organs and improves your metabolic background.",
      },
      {
        title: "Diagnosed type 2 diabetes",
        image: `${import.meta.env.BASE_URL}assets/people/audiences/diabetes.jpg`,
        imageAlt: "Man representing type 2 diabetes support goals",
        body: "If you’ve been diagnosed with type 2 diabetes — it can help better manage blood glucose, reduce food cravings, and serve as an additional therapeutic tool.",
      },
      {
        title: "Prevent fatty liver disease",
        image: `${import.meta.env.BASE_URL}assets/people/audiences/liver.jpg`,
        imageAlt: "Woman representing liver health goals",
        body: "If you aim to prevent fatty liver disease — Retatrutide may lower liver fat levels and reduce systemic inflammation.",
      },
    ],
  },
  product: {
    eyebrow: "Product",
    title: "One product. A better life.",
    name: "Retatrutide",
    dosage: "10 mg / vial",
    specs: [
      { label: "Composition", value: "Retatrutide 10 mg" },
      { label: "Category", value: "Peptide" },
      { label: "Purpose", value: "Weight loss" },
      { label: "Form", value: "Vial with lyophilized powder + 1 ml ampoule of injection water reconstitution" },
      { label: "Administration", value: "Subcutaneous injections" },
    ],
    buyCta: "Buy now",
    buyHref: "https://retatrutides.to/new/index.html",
    consultCta: "Consult an expert",
    consultHref: "https://driadashop.helpline.to/en-US/new-ticket",
    labCta: "Lab test / 99% purity",
    labHref: "#quality",
  },
  quality: {
    eyebrow: "Quality & authenticity",
    title: "Documentation you can inspect.",
    body: "The supplied laboratory report is presented alongside the product identity and batch information so the available material can be reviewed directly.",
    report: {
      title: "Laboratory analysis report",
      image: `${import.meta.env.BASE_URL}assets/documents/retatrutide-lab-report.png`,
      alt: "Laboratory analysis report for DRADA Medical Retatrutide batch 82188, reporting 10.77 mg content and 99% purity",
      date: "24 June 2026",
      batch: "82188",
      content: "10.77 mg",
      purity: "99%",
      cta: "View laboratory report",
      openLabel: "Open full-size report",
    },
    storageTitle: "How to store",
    storage: [
      "Keep the product refrigerated at 2–8°C (36–46°F).",
      "Do not freeze.",
      "Protect from light.",
      "Avoid frequent temperature changes (e.g., repeated removal from the fridge).",
      "Once reconstituted, keep refrigerated and use within approximately one month.",
    ],
    note: "Independent third-party laboratory test. Report values are reproduced from the supplied document; review the full report before relying on individual figures.",
  },
  reviews: {
    eyebrow: "Reviews",
    title: "What Our Customers Say",
    rating: "4.92 / 5",
    count: "36 forum reviews",
    sourceHref: "https://peds.to/reviews/retatrutide.157/reviews",
    secondarySourceHref: "https://www.eroids.com/reviews/driadashop.to",
    items: [
      { name: "MoltenHarbinger", rating: 5, date: "3 Aug 2026", body: "Reported feeling full sooner and finding nutrition easier to manage.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "Aki", rating: 5, date: "23 Jul 2026", body: "Noted visible progress in body composition and weight management.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "Personanongrata", rating: 5, date: "5 Jul 2026", body: "Highlighted meaningful changes in body composition while also noting side effects.", href: "https://peds.to/reviews/retatrutide.157/reviews", avatar: `${import.meta.env.BASE_URL}assets/people/reviewers/personanongrata.jpg` },
      { name: "TheGuy", rating: 5, date: "3 Jul 2026", body: "Focused on body-composition progress rather than changes on the scale alone.", href: "https://peds.to/reviews/retatrutide.157/reviews", avatar: `${import.meta.env.BASE_URL}assets/people/reviewers/theguy.jpg` },
      { name: "BrunoBertrand", rating: 5, date: "3 Jul 2026", body: "Shared a positive experience with the reviewed Retatrutide product.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "Arthuur", rating: 4, date: "7 Jul 2026", body: "Reported reduced appetite and easier adherence to a planned diet.", href: "https://peds.to/reviews/retatrutide.157/reviews", avatar: `${import.meta.env.BASE_URL}assets/people/reviewers/arthuur.jpg` },
      { name: "cokin", rating: 4, date: "24 Jul 2026", body: "Felt full faster and also documented digestive discomfort at a higher dose.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "RoselD", rating: 5, date: "22 Jun 2026", body: "Rated the overall product experience five out of five.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "sulk4", rating: 4, date: "25 Jul 2026", body: "Reported an early reduction in appetite that became less pronounced over time.", href: "https://peds.to/reviews/retatrutide.157/reviews", avatar: `${import.meta.env.BASE_URL}assets/people/reviewers/sulk4.jpg` },
      { name: "norbert", rating: 5, date: "29 Jun 2026", body: "Described faster fat-loss progress after adjusting the dose.", href: "https://peds.to/reviews/retatrutide.157/reviews", avatar: `${import.meta.env.BASE_URL}assets/people/reviewers/norbert.jpg` },
      { name: "angelgram", rating: 5, date: "26 Jun 2026", body: "Reported a broad improvement in body composition.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "blackmambata96", rating: 5, date: "17 Jun 2026", body: "Noted reduced appetite and a meaningful change in weight.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "Shiko48", rating: 5, date: "15 Jun 2026", body: "Reported lower appetite, fewer cravings, and visible weight-management progress.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "Falcon", rating: 5, date: "18 May 2026", body: "Described gradual progress after a slow start and openly documented digestive side effects.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "yey01", rating: 5, date: "13 May 2026", body: "Reported maintaining low body fat during a gaining phase, with some gastric effects.", href: "https://peds.to/reviews/retatrutide.157/reviews", avatar: `${import.meta.env.BASE_URL}assets/people/reviewers/yey01.png` },
      { name: "Emixnoise", rating: 5, date: "13 May 2026", body: "Reported fat-loss progress alongside a structured nutrition plan.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "osaid", rating: 5, date: "9 May 2026", body: "Highlighted better food control and fewer cravings.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "Lit2600", rating: 5, date: "9 May 2026", body: "Reported becoming leaner and lighter, while also noting expected side effects.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "Athanos", rating: 5, date: "9 May 2026", body: "Described relatively quick fat-loss progress and a strong overall effect.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "jny", rating: 5, date: "1 May 2026 · review 503", body: "Reported substantial weight-management progress over three months.", href: "https://peds.to/reviews/retatrutide.157/reviews" },
      { name: "jny", rating: 5, date: "1 May 2026 · review 502", body: "Rated the outcome highly and reported maintaining strength during the process.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Nasr", rating: 5, date: "1 May 2026", body: "Shared a large change in weight over less than twelve weeks and noted early nausea.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2", avatar: `${import.meta.env.BASE_URL}assets/people/reviewers/nasr.jpg` },
      { name: "Novaay", rating: 5, date: "1 May 2026", body: "Reported steady visible fat loss, stronger appetite control, and the need to stay hydrated.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "smb22", rating: 5, date: "29 Apr 2026", body: "Described strong appetite control and visible body-composition changes without notable side effects.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "MarMan", rating: 5, date: "28 Apr 2026", body: "Reported fat-loss progress and a positive overall tolerance experience.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Mr_Hybrid", rating: 5, date: "5 Apr 2026", body: "Noted reduced hunger and fewer sweet-food cravings within the first days.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Mr_Hybrid", rating: 5, date: "1 Apr 2026", body: "Reported longer satiety and fewer food cravings, with short-lived digestive discomfort.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Specko", rating: 5, date: "26 Feb 2026", body: "Described a significant body-composition change while maintaining strength.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Leodycurio", rating: 5, date: "24 Feb 2026", body: "Reported fewer cravings for highly processed food and easier diet consistency.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Loukaammari", rating: 5, date: "23 Feb 2026", body: "Reported unexpectedly rapid early weight-management progress and some nausea.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Kikito", rating: 5, date: "23 Feb 2026", body: "Noted a marked reduction in appetite and visible progress within a month.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "BloodofZeus", rating: 5, date: "23 Feb 2026", body: "Reported fewer junk-food cravings alongside a reduced interest in alcohol.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Mogger361", rating: 5, date: "23 Feb 2026", body: "Described a substantial reduction in appetite and cravings.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "lotr0510", rating: 5, date: "23 Feb 2026", body: "Reported less hunger, fewer sweet-food cravings, and steadier afternoon energy.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Seb", rating: 5, date: "20 Feb 2026", body: "Described the weight-management process as faster and easier.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2" },
      { name: "Beefym", rating: 5, date: "19 Feb 2026", body: "Reported steadier appetite and blood sugar, with modest body-composition improvement.", href: "https://peds.to/reviews/retatrutide.157/reviews?page=2", avatar: `${import.meta.env.BASE_URL}assets/people/reviewers/beefym.png` },
    ],
  },
  faqs: [
    { question: "What are the potential benefits of Retatrutide?", answer: "Weight loss, improved glucose control, reduced appetite." },
    { question: "Can Retatrutide be combined with anabolic steroids?", answer: "Yes, it can. Low doses of Retatrutide can be used to control appetite, especially during cutting cycles where maintaining a calorie deficit is important." },
    { question: "Is Retatrutide safe?", answer: "Early studies show it’s generally safe, but long-term data is limited." },
    { question: "Do I need a prescription for Retatrutide?", answer: "Yes, it's a controlled medication and requires a doctor's prescription. If you're comparing Retatrutide price or looking for a Retatrutide sale, ordering from us ensures you get one of the most competitive offers available. Just keep in mind that since it's a prescription-only product, you should be careful when transporting it across borders, as regulations may vary depending on the country." },
    { question: "How quickly will I notice results from Retatrutide?", answer: "Appetite reduction can start within the first 1–2 weeks. Noticeable weight loss typically appears after 3–4 weeks, with full effects building over several months." },
    { question: "What product is available?", answer: "Composition: Retatrutide 10 mg. Category: Peptide. Purpose: Weight loss. Form: Vial with lyophilized powder + 1 ml ampoule of injection water reconstitution. Administration: Subcutaneous injections." },
    { question: "Can I view the laboratory report?", answer: "Yes. The supplied laboratory report for DRADA MEDICAL RETATRUTIDE batch 82188 opens from the Quality & authenticity section." },
    { question: "How should Retatrutide be stored?", answer: "Keep the product refrigerated at 2–8°C (36–46°F). Do not freeze. Protect from light. Avoid frequent temperature changes. Once reconstituted, keep refrigerated and use within approximately one month." },
  ],
  footer: {
    statement: "Product information, documentation, and the next purchasing step in one place.",
    sellerNote: "For order support or product questions, contact the seller directly.",
    groups: [
      { title: "Seller & contact", links: [{ label: "Product", href: "#product" }, { label: "Buy now", href: "https://retatrutides.to/new/index.html" }, { label: "Contact information", href: "https://driadashop.helpline.to/en-US/new-ticket" }] },
    ],
    disclaimer: "Early studies show Retatrutide is generally safe, but long-term data is limited. A doctor’s prescription is required.",
  },
  mobileCta: "Buy now",
} as const;

export type SiteContent = typeof siteContent;
