export const siteContent = {
  brand: "RETATRUTIDE",
  navigation: [
    { label: "About", href: "#about" },
    { label: "How it works", href: "#how-it-works" },
    { label: "Product", href: "#product" },
    { label: "Quality", href: "#quality" },
    { label: "FAQ", href: "#faq" },
  ],
  hero: {
    eyebrow: "A focused product experience",
    title: "Retatrutide, presented with clarity.",
    body: "Essential product information, a straightforward ordering path, and support at every step.",
    primaryCta: "View the product",
    secondaryCta: "Learn more",
  },
  trustItems: [
    { title: "Laboratory report", detail: "Supplied report available to review" },
    { title: "Quality information", detail: "Product and package details in one place" },
    { title: "Batch documentation", detail: "Batch-linked report information" },
    { title: "Purchase guidance", detail: "Clear next steps before ordering" },
  ],
  whatIs: {
    eyebrow: "What is Retatrutide",
    title: "The essentials, in one place.",
    body: [
      "Retatrutide is presented here as a peptide product in a 10 mg vial format.",
      "The package identifies lyophilized powder with 1 ml water for injection and subcutaneous administration.",
    ],
    note: "Category: Peptide · Purpose: Weight loss",
  },
  howItWorks: {
    eyebrow: "How it works",
    title: "The product format, in three parts.",
    steps: [
      { number: "01", title: "Composition", body: "Retatrutide, presented as 10 mg per vial." },
      { number: "02", title: "Product form", body: "Lyophilized powder with 1 ml water for injection." },
      { number: "03", title: "Administration", body: "Presented for subcutaneous injections." },
    ],
  },
  whoFor: {
    eyebrow: "Who it is for",
    title: "Information to support an informed decision.",
    intro: "Review the product information and seek appropriate professional guidance before use.",
    cards: [
      { title: "Product information", body: "Confirm the composition, product form, and administration route." },
      { title: "Professional guidance", body: "Discuss suitability and administration with a qualified healthcare professional." },
      { title: "Before you continue", body: "Read all product information supplied with the package." },
    ],
  },
  product: {
    eyebrow: "Product",
    title: "One product. One dosage.",
    name: "Retatrutide",
    dosage: "10 mg / vial",
    description: "A single-dosage peptide presentation with the essential package information clearly set out.",
    badges: ["Single product", "Single dosage"],
    specs: [
      { label: "Composition", value: "Retatrutide 10 mg" },
      { label: "Category", value: "Peptide" },
      { label: "Purpose", value: "Weight loss" },
      { label: "Form", value: "Vial with lyophilized powder + 1 ml ampoule of water for injection" },
      { label: "Administration", value: "Subcutaneous injections" },
    ],
    cta: "View product",
    ctaHref: "#purchase",
    detailCta: "Product details",
    disclosureTitle: "Product information",
    disclosureBody: "DRADA MEDICAL Retatrutide is presented as a 10 mg vial with lyophilized powder and a 1 ml ampoule of water for injection. Administration is by subcutaneous injection.",
  },
  howToGet: {
    eyebrow: "How to get it",
    title: "A simple, supported process.",
    steps: [
      { number: "1", title: "Review", body: "Read the product, package, and laboratory information." },
      { number: "2", title: "Confirm", body: "Check suitability with a qualified healthcare professional and review purchase terms." },
      { number: "3", title: "Continue", body: "Use the purchase information below to understand the next available step." },
    ],
    cta: "Review purchase information",
    ctaHref: "#purchase",
  },
  quality: {
    eyebrow: "Quality & authenticity",
    title: "Documentation you can inspect.",
    body: "The supplied laboratory report is presented alongside the product identity so the available information can be reviewed directly.",
    report: {
      title: "Laboratory analysis report",
      image: `${import.meta.env.BASE_URL}assets/documents/retatrutide-lab-report.png`,
      alt: "Laboratory analysis report supplied for DRADA Medical Retatrutide batch 82188",
      date: "24 June 2026",
      batch: "82188",
      content: "10.77 mg",
      purity: "99%",
      cta: "View lab report",
      openLabel: "Open full-size report",
    },
    points: [
      { title: "Laboratory testing", body: "A supplied laboratory analysis report is available to open and inspect." },
      { title: "Production control", body: "Verify the seller's production-control documentation before purchase; none is published beyond the supplied lab report." },
      { title: "Batch information", body: "The supplied report identifies batch 82188 and its recorded analysis results." },
      { title: "Certificates & permissions", body: "Confirm applicable certificates and permissions with the seller before purchase." },
      { title: "Storage & handling", body: "Confirm storage and handling instructions from the package insert or seller before use." },
    ],
    note: "Report values are reproduced from the supplied document. Review the full report before relying on individual figures.",
  },
  purchase: {
    eyebrow: "Purchase, delivery & payment",
    title: "Know what to confirm before ordering.",
    cards: [
      { title: "Price & taxes", body: "Confirm the final product price and any applicable taxes on the purchasing website before payment." },
      { title: "Payment", body: "Review the payment methods offered by the seller before placing an order." },
      { title: "Delivery area", body: "Confirm that the seller delivers to your destination before ordering." },
      { title: "Delivery timing", body: "Review the seller's current delivery estimate and tracking process during purchase." },
    ],
    nextStepTitle: "Review before continuing",
    nextStepBody: "Use the product and quality sections to review the available information. The seller's external purchase destination is required to complete an order.",
    primaryCta: "Review product",
    primaryHref: "#product",
    secondaryCta: "View quality information",
    secondaryHref: "#quality",
  },
  reviews: {
    eyebrow: "Reviews",
    title: "Perspectives from across Europe.",
    notice: "Sample content — these are demonstration reviews, not verified customer testimonials.",
    items: [
      {
        initials: "AM",
        name: "Anna M.",
        country: "Germany",
        flagCode: "de",
        body: "The product information and the next steps are easy to find and understand.",
      },
      {
        initials: "CL",
        name: "Camille L.",
        country: "France",
        flagCode: "fr",
        body: "The package details and supporting document are presented in a clear, reassuring format.",
      },
      {
        initials: "SV",
        name: "Sophie V.",
        country: "Netherlands",
        flagCode: "nl",
        body: "The purchase guidance makes it clear which details should be confirmed before ordering.",
      },
    ],
  },
  faqs: [
    { question: "What product is available?", answer: "DRADA MEDICAL Retatrutide, presented as 10 mg per vial." },
    { question: "What does the package contain?", answer: "The supplied package states a vial with lyophilized powder and a 1 ml ampoule of water for injection." },
    { question: "How is the product presented for administration?", answer: "The supplied product information identifies subcutaneous injections. Seek qualified professional guidance before use." },
    { question: "Can I view the laboratory report?", answer: "Yes. The supplied laboratory analysis report can be opened from the Quality & authenticity section." },
    { question: "Is batch information available?", answer: "The supplied laboratory report identifies batch 82188. Review the full document for its recorded dates and results." },
    { question: "Where will price and taxes be shown?", answer: "Confirm the current price and any applicable taxes on the seller's purchasing website before payment." },
    { question: "How will delivery and payment work?", answer: "Available payment methods, destination coverage, and delivery estimates must be confirmed with the seller during purchase." },
    { question: "How should the product be stored?", answer: "Follow the storage instructions supplied with the product and confirm any requirements with the seller before use." },
    { question: "How do I know whether the product is suitable for me?", answer: "Review all supplied product information and discuss suitability and administration with a qualified healthcare professional." },
  ],
  footer: {
    statement: "A focused Retatrutide product experience.",
    groups: [
      {
        title: "Seller & contact",
        links: [
          { label: "Product", href: "#product" },
          { label: "Purchase information", href: "#purchase" },
          { label: "Support information", href: "#purchase" },
        ],
      },
      {
        title: "Sales & delivery",
        links: [
          { label: "Price & payment", href: "#purchase" },
          { label: "Delivery", href: "#purchase" },
          { label: "Returns", href: "#returns" },
        ],
      },
      {
        title: "Legal",
        links: [
          { label: "Privacy", href: "#privacy" },
          { label: "Cookie settings", href: "#cookies" },
          { label: "Terms", href: "#terms" },
          { label: "Regulatory information", href: "#regulatory" },
        ],
      },
    ],
    disclosures: [
      { id: "privacy", title: "Privacy", body: "This page does not transmit personal information through a form. Review the seller's privacy policy on the purchasing website before sharing personal data." },
      { id: "cookies", title: "Cookies", body: "This site uses essential cookies only. Optional analytics and marketing cookies are not active." },
      { id: "terms", title: "Terms", body: "Review the seller's purchase, payment, delivery, and return terms before placing an order." },
      { id: "returns", title: "Returns", body: "Return eligibility and instructions must be confirmed with the seller before purchase." },
      { id: "regulatory", title: "Regulatory information", body: "Product suitability, permissions, and any applicable regulatory documentation must be verified with the seller and a qualified healthcare professional." },
    ],
    disclaimer: "Review the product information and consult a qualified healthcare professional before use.",
  },
  mobileCta: "View product",
} as const;

export type SiteContent = typeof siteContent;
